{
    'name': 'PO Lifecycle',
    'version': '19.0.1.0.0',
    'summary': 'Full Purchase Order lifecycle workflow with accounting integration',
    'author': 'Farage Printing Industries',
    'category': 'Purchase',
    'depends': [
        'base', 'mail', 'project_lifecycle', 'purchase', 'hr', 'base_setup',
    ],
    'data': [
        'security/res_groups.xml',
        'security/ir.model.access.csv',
        'security/record_rules.xml',
        'data/sequences.xml',
        'data/currency_activation.xml',
        'data/res_config_defaults.xml',
        'views/po_admin_assignment_views.xml',
        'views/po_lifecycle_item_views.xml',
        'views/po_lifecycle_views.xml',
        'views/project_project_views.xml',
        'views/res_config_settings_views.xml',
        'views/wizards.xml',
        'views/menus.xml',
        'report/po_cost_report_action.xml',
        'report/po_cost_report_template.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
