[options]
db_host = localhost
db_port = 5432
db_name = FNC
db_user = odoo
db_password = odoo
addons_path = odoo/addons,custom_addons
default_productivity_apps = True
admin_passwd = $pbkdf2-sha512$600000$AGCsdS7l/L8XonROCcE4Rw$o7L/h1qha5MWAk5lhr81HKbjgA0sv2Unffesk/Y.VS4v.4MMJ1f.SHTA721EwVuIhhVjocNr9c/G2V3gy.y2Tw

